artifact_uri: /home/jibach/End-to-End-Breast-Cancer-Prediction-ML-Pipeline/mlflow_tracking/216368620867244950/d2f8870e88d44e1b96b05f68c9bdce0f/artifacts
end_time: 1778909628262
entry_point_name: ''
experiment_id: '216368620867244950'
lifecycle_stage: active
run_id: d2f8870e88d44e1b96b05f68c9bdce0f
run_name: training_all_models
source_name: ''
source_type: 4
source_version: ''
start_time: 1778909600513
status: 3
tags: []
user_id: jibach
