artifact_uri: /home/jibach/End-to-End-Breast-Cancer-Prediction-ML-Pipeline/mlflow_tracking/216368620867244950/74143e33360f4c3eafac92162aa821b7/artifacts
end_time: 1778909607970
entry_point_name: ''
experiment_id: '216368620867244950'
lifecycle_stage: active
run_id: 74143e33360f4c3eafac92162aa821b7
run_name: random_forest
source_name: ''
source_type: 4
source_version: ''
start_time: 1778909603607
status: 3
tags: []
user_id: jibach
