artifact_uri: /home/jibach/End-to-End-Breast-Cancer-Prediction-ML-Pipeline/mlflow_tracking/216368620867244950/e20b91b2f64e4ace96838bae69485a02/artifacts
end_time: 1778910380621
entry_point_name: ''
experiment_id: '216368620867244950'
lifecycle_stage: active
run_id: e20b91b2f64e4ace96838bae69485a02
run_name: random_forest
source_name: ''
source_type: 4
source_version: ''
start_time: 1778910376199
status: 3
tags: []
user_id: jibach
