artifact_uri: /home/jibach/End-to-End-Breast-Cancer-Prediction-ML-Pipeline/mlflow_tracking/216368620867244950/c3c2e7f7ab934eccb5863ead94128c52/artifacts
end_time: 1778911028416
entry_point_name: ''
experiment_id: '216368620867244950'
lifecycle_stage: active
run_id: c3c2e7f7ab934eccb5863ead94128c52
run_name: xgboost
source_name: ''
source_type: 4
source_version: ''
start_time: 1778911025254
status: 3
tags: []
user_id: jibach
