artifact_uri: /home/jibach/End-to-End-Breast-Cancer-Prediction-ML-Pipeline/mlflow_tracking/216368620867244950/b0ccb35dcc76434fbfe3dfe36b7e970d/artifacts
end_time: 1778910376195
entry_point_name: ''
experiment_id: '216368620867244950'
lifecycle_stage: active
run_id: b0ccb35dcc76434fbfe3dfe36b7e970d
run_name: logistic_regression
source_name: ''
source_type: 4
source_version: ''
start_time: 1778910373010
status: 3
tags: []
user_id: jibach
