artifact_uri: /home/jibach/End-to-End-Breast-Cancer-Prediction-ML-Pipeline/mlflow_tracking/216368620867244950/7c6b3dc1b25e4df3b4848cab9b7b7019/artifacts
end_time: 1778911741041
entry_point_name: ''
experiment_id: '216368620867244950'
lifecycle_stage: active
run_id: 7c6b3dc1b25e4df3b4848cab9b7b7019
run_name: logistic_regression
source_name: ''
source_type: 4
source_version: ''
start_time: 1778911737671
status: 3
tags: []
user_id: jibach
