artifact_uri: /home/jibach/End-to-End-Breast-Cancer-Prediction-ML-Pipeline/mlflow_tracking/216368620867244950/1099bc58bcb847ba8d3785bcfdd46d35/artifacts
end_time: 1778912085705
entry_point_name: ''
experiment_id: '216368620867244950'
lifecycle_stage: active
run_id: 1099bc58bcb847ba8d3785bcfdd46d35
run_name: random_forest
source_name: ''
source_type: 4
source_version: ''
start_time: 1778912080789
status: 3
tags: []
user_id: jibach
