artifact_uri: /home/jibach/End-to-End-Breast-Cancer-Prediction-ML-Pipeline/mlflow_tracking/216368620867244950/a0d8b9b97e024c2c8bf088cec77d0891/artifacts
end_time: 1778911765768
entry_point_name: ''
experiment_id: '216368620867244950'
lifecycle_stage: active
run_id: a0d8b9b97e024c2c8bf088cec77d0891
run_name: training_all_models
source_name: ''
source_type: 4
source_version: ''
start_time: 1778911737533
status: 3
tags: []
user_id: jibach
